name: publish

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:

  publish:
    runs-on: ubuntu-latest
    env:
      SNOWPLOW_CONSOLE_ORG_ID: ${{ secrets.SNOWPLOW_CONSOLE_ORG_ID }}
      SNOWPLOW_CONSOLE_API_KEY_ID: ${{ secrets.SNOWPLOW_CONSOLE_API_KEY_ID }}
      SNOWPLOW_CONSOLE_API_KEY: ${{ secrets.SNOWPLOW_CONSOLE_API_KEY_SECRET }}
      SNOWPLOW_CONSOLE_MANAGED_FROM: ${{ github.server_url }}/${{ github.repository }}

    steps:
      - uses: actions/checkout@v4

      - uses: snowplow-product/setup-snowplow-cli@v1

      - run: |
          if [ ${{github.ref_name}} = "main" ]; then
            echo "SNP_ENV=prod" >> $GITHUB_ENV
          elif [ ${{github.ref_name}} = "develop" ]; then
            echo "SNP_ENV=dev" >> $GITHUB_ENV
          else
            echo "::error ::should only run on main or develop"
            exit 1
          fi

      - name: Validate domain restrictions
        run: |
          # Check data structure vendors
          echo "Checking data structure vendors..."
          for file in $(find data-structures -name "*.yaml" -o -name "*.yml"); do
            echo "Checking file: $file"
            vendor=$(grep -A 10 "self:" "$file" | grep "vendor:" | sed 's/.*vendor: *//' | tr -d ' ')
            if [ ! -z "$vendor" ] && [ "$vendor" != ${{ secrets.VENDOR }} ]; then
              echo "❌ ERROR: Data structure in $file has vendor '$vendor'"
              echo "   Only vendor '${{ secrets.VENDOR }}' is allowed for this repository"
              exit 1
            fi
            if [ ! -z "$vendor" ]; then
              echo "✅ Valid vendor: $vendor in $file"
            fi
          done
          
          # Check data product domains
          echo "Checking data product domains..."
          for file in $(find data-products -name "*.yaml" -o -name "*.yml" | grep -v "source-apps"); do
            echo "Checking file: $file"
            domain=$(grep "domain:" "$file" | sed 's/.*domain: *//' | tr -d ' ')
            if [ ! -z "$domain" ] && [ "$domain" != ${{ secrets.DOMAIN }} ]; then
              echo "❌ ERROR: Data product in $file has domain '$domain'"
              echo "   Only domain '${{ secrets.DOMAIN }}' is allowed for this repository"
              exit 1
            fi
            if [ ! -z "$domain" ]; then
              echo "✅ Valid domain: $domain in $file"
            else
              echo "⚠️  WARNING: Data product in $file has no domain specified"
              echo "   Please add 'domain: dev_ops' to the data section"
              exit 1
            fi
          done
          
          echo "✅ All domain restrictions validated successfully!"

      - name: validate data structures
        run: snowplow-cli ds validate data-structures --gh-annotate

      - name: validate data products
        run: snowplow-cli dp validate data-products --gh-annotate

      - name: publish data structures
        run: snowplow-cli ds pub ${{ env.SNP_ENV }} ./data-structures

      - name: publish data products
        run: snowplow-cli dp pub ${{ env.SNP_ENV }} ./data-products
