name: validate

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:

  validate:
    runs-on: ubuntu-latest
    env:
      SNOWPLOW_CONSOLE_ORG_ID: ${{ secrets.SNOWPLOW_CONSOLE_ORG_ID }}
      SNOWPLOW_CONSOLE_API_KEY_ID: ${{ secrets.SNOWPLOW_CONSOLE_API_KEY_ID }}
      SNOWPLOW_CONSOLE_API_KEY: ${{ secrets.SNOWPLOW_CONSOLE_API_KEY_SECRET }}

    steps:
      - uses: actions/checkout@v4
      - uses: snowplow-product/setup-snowplow-cli@v1

      - name: Validate domain restrictions
        run: |
          # Check data structure vendors
          echo "Checking data structure vendors..."
          for file in $(find data-structures -name "*.yaml" -o -name "*.yml"); do
            echo "Checking file: $file"
            vendor=$(grep -A 10 "self:" "$file" | grep "vendor:" | sed 's/.*vendor: *//' | tr -d ' ')
            if [ ! -z "$vendor" ] && [ "$vendor" != "${{ env.VENDOR }}" ]; then
              echo "❌ ERROR: Data structure in $file has vendor '$vendor'"
              echo "   Only vendor '${{ env.VENDOR }}' is allowed for this repository"
              exit 1
            fi
            if [ ! -z "$vendor" ]; then
              echo "✅ Valid vendor: $vendor in $file"
            fi
          done
          
          # Check data product domains
          echo "Checking data product domains..."
          for file in $(find data-products -name "*.yaml" -o -name "*.yml" | grep -v "source-apps"); do
            echo "Checking file: $file"
            domain=$(grep "domain:" "$file" | sed 's/.*domain: *//' | tr -d ' ')
            if [ ! -z "$domain" ] && [ "$domain" != "${{ env.DOMAIN }}" ]; then
              echo "❌ ERROR: Data product in $file has domain '$domain'"
              echo "   Only domain '${{ env.DOMAIN }}' is allowed for this repository"
              exit 1
            fi
            if [ ! -z "$domain" ]; then
              echo "✅ Valid domain: $domain in $file"
            else
              echo "⚠️  WARNING: Data product in $file has no domain specified"
              echo "   Please add 'domain: dev_ops' to the data section"
              exit 1
            fi
          done
          
          echo "✅ All domain restrictions validated successfully!"

      - name: validate data structures
        run: snowplow-cli ds validate data-structures --gh-annotate

      - name: validate data products
        run: snowplow-cli dp validate data-products --gh-annotate
